# This is a basic workflow to help you get started with Actions

name: zeroqueue-build

on:
  push:
    branches: [master]
  pull_request:
    branches: [ master ]


jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: nelonoel/branch-name@v1
    - uses: actions/checkout@v2
    - name: docker login and build
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        GITHUB_RUN_ID: ${{ github.run_id }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker build -t nicksolante1/new-repo:${BRANCH_NAME}${{ env.GITHUB_RUN_ID }} .

  push-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
    - uses: nelonoel/branch-name@v1
    - name: docker push
      run: |
        docker push nicksolante1/new-repo:${BRANCH_NAME}${{ env.GITHUB_RUN_ID }}

  pull-image:
    runs-on: ubuntu-latest
    needs: push-image
    steps:
    - uses: nelonoel/branch-name@v1
    - name: docker pull
      run: |
       docker pull nicksolante1/new-repo:${BRANCH_NAME}${{ env.GITHUB_RUN_ID }}

  lint:
    runs-on: ubuntu-latest
    needs: pull-image
    steps:
    - uses: nelonoel/branch-name@v1
    - name: docker run
      run: |
       docker run --publish 8000:9376 --detach --name bb nicksolante1/new-repo:${BRANCH_NAME}${{ env.GITHUB_RUN_ID }} 'npm install --dev && npm run lint'